### ISSUE TITLE
App.js and Server.js

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#113]
Guys, these app.js don't follow coding convention (need to add comments for each query, **CamelCase** file names and **camelCase** names for objects/methods and has a bunch of commented code everywhere (please delete!) AND PLEASE put queries and imports IN A SINGLE LINE.

**Please fix this ASAP  YOU GUYS DO THIS DIRECTLY ON PRE_RELEASE BRANCH ASAP.** 
-------------------------------------------------
For **Next Sprint**, we gotta organize the app.js into folder with multiple pages, its a huge file! So the queries need to be put into pages according to the corresponding front pages they are being called in, and then we can just add the "require" method for each page in the server.js.

THIS will be done next sprint!

**Comment by malhimaira** [comment]
AND MAKE SURE THE CODE WORKS.

**Comment by JeffreyCHChan** [comment]
to be done:

- query helper function
- separation of concerns where we split the API calls into the respective files

**Comment by malhimaira** [comment]
Please close if this is complete!
