### ISSUE TITLE
Testing Unit and Integration

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#117]
Backend, you guys need to complete the unit and integrations tests.

Everyone do unit tests for all code. 

@JosephMezza pls do unit tests for both mine and Jon/Mikes query code.

@JGambino00 @giroux2000 both of you do unit and as soon as its ready, let me know and inform @JeffreyCHChan and @JosephMezza so that this can get done for remaining code.

**Comment by malhimaira** [comment]
https://docs.google.com/document/d/1mRb2XdqH6pPsgkxxwecnyxcXYZxV1bW8ho2lNp3nRvQ/edit

Please document your tests in the EDGE CASE TESTS Table, try to cover and fix as much as you can otherwise tie a bug.

**Comment by JosephMezza** [comment]
Tests have been completed for all of my backend code
