### ISSUE TITLE
Database: Finalize and Refractor final database and ERD

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#119]
Please refractor and finalize database  (inserts, structure, etc) for this sprint and make sure it works with code AND update final documentation

**Comment by leoenix** [comment]
currently working 3/14 6:35. will wait for bug fixes to see if additional changes are needed

**Comment by leoenix** [comment]
ER and component diagram documentation updated in sprint 3 final doc
