### ISSUE TITLE
DOCUMENTATION

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#125]
Base Template for Presentation: @malhimaira 

Sprint Retrospective/Summary of this sprint (ev/av) /Release Plan: @malhimaira 
I'm going to add USP for each bug fixed, thus I will make the summary table of USER STORIES for this sprint completed

Backlog Update and number of stories left, : @jongjonathan 

Software Architecture Document @leoenix @JGambino00 @giroux2000 @JosephMezza 
Please Update the ERD, Component Diagram and Api model! I am putting a change log in sprint 3 document for changes in our models, please record any changes and reasoning!

Risk @JeffreyCHChan please update any changes

UI @narroarrow pls have done asap when I send the UI for this sprint and next sprint

Testing EVERYONE please update the acceptance tests for this sprint with comments and pass!
@giroux2000 just add a small paragraph about what we are doing for integrations tests, I will put the updated acceptance tests @malhimaira

**Comment by JosephMezza** [comment]
Domain Model and API Diagram have been updated along with their changelogs
