### ISSUE TITLE
Refractor the queries, axios everywhere, and in Notifications DoctorDashboard and app in app.js

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#128]
Hey @JosephMezza so some of the Axios are using "Axios.post" instead of "Axios.get" and vice versa for your queries  in DoctorDashboard, and the same issue in the app.js file, some if the queries are "app.post" instead of "app.get" and vice versa. make sure to use the correct call!

EXAMPLE In DoctorDashboard, this should by a "Axios.get" since we are not writing to db here
`  function getAllNotifications(){//This will return patient name, and appointment time
    Axios.post("http://localhost:8080/retrieveAllNotifications", {
      params: {
        id: localStorage.getItem('id')
      }
    }).then((response)=>{
      setNotificationsList(response.data);
      console.log("Notification List:");
      console.log(response.data);  
  });  
  }`

and its corresponding query in App.js should be "app.get" since its a get and not a post (only fetching, no writing)

` app.post("/retrieveAllNotifications", (req,res) =>{ 
    let doctorID = req.query["id"];
    db.query("SELECT Upatient.Fname, Upatient.Lname, A.aptDate, A.startTime, A.endTime " +
    "FROM 390db.Appointments A, 390db.Users Upatient, 390db.Doctors D, 390db.Patients P " +
    "Where A.PatientID = Upatient.ID AND A.doctorID = ? AND P.id=Upatient.id AND P.doctorID = D.id;", [doctorID], (err, result) =>{
        if(err){
            console.log(err);
        } else{
            res.send(result);
        }
    })
 });`

Ask @alexbara2000 if u need help, @JosephMezza pls double check all the ones u did are correct, the notifications one need to be fixed so far, there may be others

**Comment by JosephMezza** [comment]
I will begin working on this for Sprint 4
