### ISSUE TITLE
Refractor Doctor Patient Pages depending on Users SPRINT 4

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#131]
SPRINT 4 Enhancement

Can we make a single page for Doctor, Health, Immigration Admin to access the list of patient profiles NEXT SPRINT. Because all the pages are the same, just display different values, we can technically have one page . So depending on the logged in user, we can display  the right values.

**Comment by malhimaira** [comment]
Don't Fix until next sprint please!

**Comment by malhimaira** [comment]
@leoenix Hey, I just tested this and with the new change, now admins can view the page but not doctors!

**Comment by malhimaira** [comment]
so I changed it back, hopefully we can fix this next sprint

**Comment by leoenix** [comment]
@malhimaira sorry i went too quick. corrected and tested 

1) access when admin works
2) access when doctor works
3) redirect when logged out works
4) redirect when role is not admin or doctor works
