### ISSUE TITLE
Refractor Admin's profile pages 

### ISSUE THREAD

**Issue by alexbara2000** [JeffreyCHChan/SOEN390#133]

**Comment by malhimaira** [comment]
I think we will need to decide if we want this page still

**Comment by malhimaira** [comment]
Refractor admin pages to be one page for editing doctors, health officials and immigration officers where admin can admit or deny

And another page with the patient list and where they can reasign

(move the patient part of current admindashboard to a separate page and add the reassignment feature there)

and remove the old doctor patient profile page from admin view

**Comment by malhimaira** [comment]
I will just do this since I am working with Max
