### ISSUE TITLE
moving method calls from app.js to other files

### ISSUE THREAD

**Issue by JeffreyCHChan** [JeffreyCHChan/SOEN390#141]
current attempts have been done on get call for seeOpenAppointments on the refactorBackend branch

- at the current moment the return from the query method call is undefined but within the method the data does exists
- methods "getNextDayOfTheWeek" and "arrayMaker" have been moved but no luck on testing as the procedure for querying was changed

**Comment by JeffreyCHChan** [comment]
possibly making it async will help 

https://askubuntu.com/questions/1046687/node-js-userlogged-function-returning-undefined-why 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by malhimaira** [comment]
Can you pls o=close and transfer whatever is left on issue #113 here bc its the same thing @JeffreyCHChan
