### ISSUE TITLE
Patient see their current scheduled appointment

### ISSUE THREAD

**Issue by malhimaira** [JeffreyCHChan/SOEN390#161]
Hey guys, I just realized, can the patient view when their upcoming booking for appointment is? If possible by Sunday can u pls add this to the patient appointment page .

**Comment by JeffreyCHChan** [comment]
they can not but are we looking to add this now? or can we do an email? 

It can be done in 5 minutes if we want it on the website

**Comment by malhimaira** [comment]
Yeah it should be displayed on website, can u pls add this? @JeffreyCHChan

**Comment by malhimaira** [comment]
bc I don't see it anywhere
